import { NextRequest } from 'next/server';
import { randomBytes } from 'crypto';

const LOOPBACK_HOSTS = new Set(['127.0.0.1', 'localhost', '::1']);

// C-3: Auto-generate a per-session exec token if none is configured.
// This prevents local processes from spoofing Origin headers to bypass auth.
let autoGeneratedToken: string | null = null;

function getExecToken(): string {
  const envToken = process.env.CHAINMIND_EXEC_TOKEN || '';
  if (envToken) return envToken;

  // Auto-generate once per process lifetime
  if (!autoGeneratedToken) {
    autoGeneratedToken = randomBytes(32).toString('hex');
    // Inject into env so Next.js API routes can read it
    process.env.CHAINMIND_EXEC_TOKEN = autoGeneratedToken;
  }
  return autoGeneratedToken;
}

// Expose for Electron main process to read and inject into preload
export function getOrCreateExecToken(): string {
  return getExecToken();
}

function normalizeHost(rawHost: string): string {
  if (!rawHost) return '';
  if (rawHost.startsWith('[')) {
    const end = rawHost.indexOf(']');
    return end > 0 ? rawHost.slice(1, end) : rawHost;
  }
  const idx = rawHost.indexOf(':');
  return idx >= 0 ? rawHost.slice(0, idx) : rawHost;
}

function isLoopbackHost(req: NextRequest): boolean {
  const host = normalizeHost(req.headers.get('host') || '');
  return LOOPBACK_HOSTS.has(host);
}

function getExpectedOrigin(): string {
  const host = process.env.HOSTNAME || '127.0.0.1';
  const port = process.env.PORT || '3456';
  return `http://${host}:${port}`;
}

function getRequestOrigin(req: NextRequest): string {
  const origin = req.headers.get('origin');
  if (origin) return origin;

  const referer = req.headers.get('referer');
  if (!referer) return '';

  try {
    return new URL(referer).origin;
  } catch {
    return '';
  }
}

export function isTrustedElectronRequest(req: NextRequest): boolean {
  if (process.env.ELECTRON !== '1') return false;
  if (!isLoopbackHost(req)) return false;
  const expectedOrigin = getExpectedOrigin();
  const origin = getRequestOrigin(req);
  return origin === expectedOrigin;
}

export function isAuthorizedExecRequest(req: NextRequest): boolean {
  // C-3: Always use token-based auth — Origin headers can be spoofed by local processes.
  // getExecToken() auto-generates a token if CHAINMIND_EXEC_TOKEN is not set.
  const token = getExecToken();
  if (token) {
    return (req.headers.get('x-exec-token') || '') === token;
  }
  // Fallback only if token generation somehow failed
  return isTrustedElectronRequest(req);
}
